// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyActYtHvwT8vue5mDWeJ4i2mGWdly25xt0',
    appId: '1:898168480745:web:23fb0044c3c32dffe7e178',
    messagingSenderId: '898168480745',
    projectId: 'sample-d919a',
    authDomain: 'sample-d919a.firebaseapp.com',
    storageBucket: 'sample-d919a.appspot.com',
    measurementId: 'G-MEG27FERWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw9kf2KYdVaVjW8VQVxrCC8j3636gDApE',
    appId: '1:898168480745:android:e3808b51916e6893e7e178',
    messagingSenderId: '898168480745',
    projectId: 'sample-d919a',
    storageBucket: 'sample-d919a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuxMzuXjyt6SrX9N2s0MJkd-b-7cA0_OM',
    appId: '1:898168480745:ios:34ddd5bacc6cd555e7e178',
    messagingSenderId: '898168480745',
    projectId: 'sample-d919a',
    storageBucket: 'sample-d919a.appspot.com',
    iosClientId: '898168480745-vkhmrn79304pfahif3b724cqb506rcp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.crossroads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuxMzuXjyt6SrX9N2s0MJkd-b-7cA0_OM',
    appId: '1:898168480745:ios:34ddd5bacc6cd555e7e178',
    messagingSenderId: '898168480745',
    projectId: 'sample-d919a',
    storageBucket: 'sample-d919a.appspot.com',
    iosClientId: '898168480745-vkhmrn79304pfahif3b724cqb506rcp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.crossroads',
  );
}
